name: ovn-chassis
version: 21.09.0
base: core20
summary: Open Virtual Network Chassis
description: |
  OVN (Open Virtual Network) chassis snap
grade: devel
confinement: strict
environment:
  LC_ALL: C
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  # Openvswitch
  ovs-vswitchd:
    command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor start
    stop-command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    after: [ovsdb-server]
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      # NETLINK_NETFILTER SOCK_RAW sockets
      - firewall-control
      - openvswitch-support
      - process-control
      - system-trace
      - hardware-observe
      - hugepages-control
      - microstack-support
  ovsdb-server:
    command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor start
    stop-command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support

  # OVN
  ovn-controller:
    command: bin/ovn-wrapper $SNAP/usr/share/ovn/scripts/ovn-ctl start_controller --no-monitor
    stop-command: bin/ovn-wrapper $SNAP/usr/share/ovn/scripts/ovn-ctl stop_controller --no-monitor --restart
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support
    after:
      - ovsdb-server
      - ovs-vswitchd

  # OVS/OVN cli tools
  ovn-appctl:
    command: bin/ovn-wrapper $SNAP/usr/bin/ovn-appctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-trace:
    command: bin/ovn-wrapper $SNAP/usr/bin/ovn-trace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-detrace:
    command: bin/ovn-wrapper $SNAP/usr/bin/ovn-detrace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-nbctl:
    command: bin/ovn-wrapper $SNAP/usr/bin/ovn-nbctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-sbctl:
    command: bin/ovn-wrapper $SNAP/usr/bin/ovn-sbctl
    plugs:
      - network
      - network-bind
      - process-control
      - microstack-support

  ovs-vsctl:
    command: bin/ovs-wrapper $SNAP/usr/bin/ovs-vsctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-appctl:
    command: bin/ovs-wrapper $SNAP/usr/bin/ovs-appctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-ofctl:
    command: bin/ovs-wrapper $SNAP/usr/bin/ovs-ofctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-dpctl:
    command: bin/ovs-wrapper $SNAP/usr/bin/ovs-dpctl
    plugs:
      - network
      - process-control
      - microstack-support

parts:
  # Add Ubuntu Cloud Archive sources.
  # Allows us to fetch things such as updated libvirt.
  uca-sources:
    plugin: nil
    build-packages:
      - ubuntu-cloud-keyring
      - software-properties-common
      - dpkg-dev  # We'll need to manipulate sources later.
      # The two dependencies below are added to avoid errors during
      # the build step of the openstack-projects part (see LP: #1864589).
      - python3-dev
      - python3-distutils
    override-pull: |
      add-apt-repository -s cloud-archive:xena
      apt-key update
      apt update
      snapcraftctl pull

  hypervisor:
    plugin: nil
    after:
      - ovs-wrapper
      - ovn-wrapper
      - uca-sources
    stage-packages:
      - openvswitch-switch
      - ovn-host
    organize:
       # Deal with alternatives usage in deb packages.
       usr/lib/openvswitch-switch/ovs-vswitchd: usr/sbin/ovs-vswitchd

  ovs-wrapper:
    source: ./snap/local/snap-wrappers/ovs
    plugin: dump
    organize:
      ovs-wrapper: bin/ovs-wrapper

  ovn-wrapper:
    source: ./snap/local/snap-wrappers/ovn
    plugin: dump
    organize:
      ovn-wrapper: bin/ovn-wrapper
