name: ovn-chassis
version: 21.09.0
base: core20
summary: Open vSwitch and Open Virtual Network chassis components
description: |
 The ovn-chassis snap provides Open vSwitch (OVS) and the Open Virtual Network
 (OVN) distributed controller.  Together they form the data plane components
 of OVN.

 Open vSwitch is a multilayer software switch.  OVS's goal is to implement a
 production quality switch platform that supports standard management
 interfaces and opens the forwarding functions to programmatic extension and
 control.

 OVN, the Open Virtual Network, is a system to support virtual network
 abstraction.  OVN complements the existing capabilities of OVS to add
 native support for virtual network abstractions, such as virtual L2 and L3
 overlays and security groups.
grade: devel
confinement: strict
environment:
  LC_ALL: C
  PATH: usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH
  # OVN runtime configuration
  OVN_LOGDIR: $SNAP_COMMON/log/ovn
  OVN_RUNDIR: $SNAP_COMMON/run/ovn
  OVN_SYSCONFDIR: $SNAP_COMMON/etc
  OVN_PKGDATADIR: $SNAP/usr/share/ovn
  OVN_BINDIR: $SNAP/usr/bin
  OVN_SBINDIR: $SNAP/usr/sbin
  # OVS runtime configuration
  OVS_LOGDIR: $SNAP_COMMON/log/openvswitch
  OVS_RUNDIR: $SNAP_COMMON/run/openvswitch
  OVS_SYSCONFDIR: $SNAP_COMMON/etc
  OVS_PKGDATADIR: $SNAP/usr/share/openvswitch
  OVS_BINDIR: $SNAP/usr/bin
  OVS_SBINDIR: $SNAP/usr/sbin

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  # Openvswitch
  ovs-vswitchd:
    command: usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor start
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    after: [ovsdb-server]
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      # NETLINK_NETFILTER SOCK_RAW sockets
      - firewall-control
      - openvswitch-support
      - process-control
      - system-trace
      - hardware-observe
      - hugepages-control
      - microstack-support
  ovsdb-server:
    command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor start
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support

  # OVN
  ovn-controller:
    command: usr/share/ovn/scripts/ovn-ctl start_controller --no-monitor
    stop-command: usr/share/ovn/scripts/ovn-ctl stop_controller --no-monitor --restart
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support
    after:
      - ovsdb-server
      - ovs-vswitchd

  # OVS/OVN cli tools
  ovn-appctl:
    command: usr/bin/ovn-appctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-trace:
    command: usr/bin/ovn-trace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-detrace:
    command: usr/bin/ovn-detrace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-nbctl:
    command: usr/bin/ovn-nbctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-sbctl:
    command: usr/bin/ovn-sbctl
    plugs:
      - network
      - network-bind
      - process-control
      - microstack-support

  ovs-vsctl:
    command: usr/bin/ovs-vsctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-appctl:
    command: usr/bin/ovs-appctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-ofctl:
    command: usr/bin/ovs-ofctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-dpctl:
    command: usr/bin/ovs-dpctl
    plugs:
      - network
      - process-control
      - microstack-support

parts:
  # Add Ubuntu Cloud Archive sources.
  # Allows us to fetch things such as updated libvirt.
  uca-sources:
    plugin: nil
    build-packages:
      - ubuntu-cloud-keyring
      - software-properties-common
      - dpkg-dev  # We'll need to manipulate sources later.
      # The two dependencies below are added to avoid errors during
      # the build step of the openstack-projects part (see LP: #1864589).
      - python3-dev
      - python3-distutils
    override-pull: |
      add-apt-repository -s cloud-archive:xena
      apt-key update
      apt update
      snapcraftctl pull

  hypervisor:
    plugin: nil
    after:
      - uca-sources
    stage-packages:
      - openvswitch-switch
      - openvswitch-switch-dpdk
      - ovn-host
    organize:
       # Deal with alternatives usage in deb packages.
       usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk: usr/sbin/ovs-vswitchd

  ovs-wrapper:
    source: ./snap/local/snap-wrappers/ovs
    plugin: dump
    organize:
      ovs-wrapper: bin/ovs-wrapper
