name: ovn-chassis
adopt-info: ovn
base: core22
summary: Open vSwitch and Open Virtual Network chassis components
description: |
 The ovn-chassis snap provides Open vSwitch (OVS) and the Open Virtual Network
 (OVN) distributed controller.  Together they form the data plane components
 of OVN.

 Open vSwitch is a multilayer software switch.  OVS's goal is to implement a
 production quality switch platform that supports standard management
 interfaces and opens the forwarding functions to programmatic extension and
 control.

 OVN, the Open Virtual Network, is a system to support virtual network
 abstraction.  OVN complements the existing capabilities of OVS to add
 native support for virtual network abstractions, such as virtual L2 and L3
 overlays and security groups.
icon: snap/local/ovn-logo.png
grade: stable
license: Apache-2.0 OR BSD-3-Clause OR BSD-2-Clause OR GPL-2.0-only OR LGPL-2.1-only OR SISSL OR ISC OR Unlicense
confinement: strict
environment:
  LC_ALL: C
  PATH: usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH
  # OVN runtime configuration
  OVN_LOGDIR: $SNAP_COMMON/log/ovn
  OVN_RUNDIR: $SNAP_COMMON/run/ovn
  OVN_SYSCONFDIR: $SNAP_COMMON/etc
  OVN_PKGDATADIR: $SNAP/usr/share/ovn
  OVN_BINDIR: $SNAP/usr/bin
  OVN_SBINDIR: $SNAP/usr/sbin
  # OVS runtime configuration
  OVS_LOGDIR: $SNAP_COMMON/log/openvswitch
  OVS_RUNDIR: $SNAP_COMMON/run/openvswitch
  OVS_SYSCONFDIR: $SNAP_COMMON/etc
  OVS_PKGDATADIR: $SNAP/usr/share/openvswitch
  OVS_BINDIR: $SNAP/usr/bin
  OVS_SBINDIR: $SNAP/usr/sbin

apps:
  # Openvswitch
  ovs-vswitchd:
    command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor start
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    after: [ovsdb-server]
    daemon: forking
    refresh-mode: endure
    plugs:
      - network
      - network-bind
      - network-control
      # NETLINK_NETFILTER SOCK_RAW sockets
      - firewall-control
      - openvswitch-support
      - process-control
      - system-trace
      - hardware-observe
      - hugepages-control
  ovsdb-server:
    command: bin/ovs-wrapper $SNAP/usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd --no-monitor start
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    refresh-mode: endure
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace

  # OVN
  ovn-controller:
    command: usr/share/ovn/scripts/ovn-ctl start_controller --no-monitor
    stop-command: usr/share/ovn/scripts/ovn-ctl stop_controller --no-monitor --restart
    daemon: forking
    refresh-mode: endure
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - hardware-observe
    after:
      - ovsdb-server
      - ovs-vswitchd

  # OVS/OVN cli tools
  ovn-appctl:
    command: usr/bin/ovn-appctl
    plugs:
      - network
      - network-bind
  ovn-trace:
    command: usr/bin/ovn-trace
    plugs:
      - network
      - network-bind
  # The 22.03 package does currently not include the ovn-detrace binary, put
  # this back once resolved. LP: #1971178
  # ovn-detrace:
  #   command: usr/bin/ovn-detrace
  #   plugs:
  #     - network
  #     - network-bind
  ovn-nbctl:
    command: usr/bin/ovn-nbctl
    plugs:
      - network
      - network-bind
  ovn-sbctl:
    command: usr/bin/ovn-sbctl
    plugs:
      - network
      - network-bind
      - process-control

  ovs-vsctl:
    command: usr/bin/ovs-vsctl
    plugs:
      - network
      - process-control
  ovs-appctl:
    command: usr/bin/ovs-appctl
    plugs:
      - network
      - process-control
  ovs-ofctl:
    command: usr/bin/ovs-ofctl
    plugs:
      - network
      - process-control
  ovs-dpctl:
    command: usr/bin/ovs-dpctl
    plugs:
      - network
      - process-control

parts:
  ovs:
    plugin: autotools
    source: https://github.com/openvswitch/ovs.git
    source-type: git
    source-branch: branch-3.0
    build-environment:
      - CONFIGURE_PARAMETERS: --prefix=/usr --localstatedir=/var --enable-ssl --sysconfdir=/etc --with-dpdk=shared
      - on s390x:
        - CONFIGURE_PARAMETERS: --prefix=/usr --localstatedir=/var --enable-ssl --sysconfdir=/etc
    override-build: |
      ./boot.sh
      ./configure $CONFIGURE_PARAMETERS
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      make install DESTDIR=$CRAFT_PART_INSTALL
      make check TESTSUITEFLAGS="-j$CRAFT_PARALLEL_BUILD_COUNT"
    build-packages:
      - autoconf
      - automake
      - bzip2
      - dh-python
      - graphviz
      - iproute2
      - libcap-ng-dev
      - libdbus-1-dev
      - libnuma-dev
      - libpcap-dev
      - libssl-dev
      - libtool
      - libunbound-dev
      - openssl
      - pkg-config
      - procps
      - python3-all-dev
      - python3-setuptools
      - python3-sortedcontainers
      - python3-sphinx
      - on amd64:
        - libdpdk-dev
      - on arm64:
        - libdpdk-dev
      - on ppc64el:
        - libdpdk-dev
    stage-packages:
      - libevent-2.1-7
      - libunbound8
      - python3-sortedcontainers
      - on amd64:
        - dpdk
        - librte-meta-net
      - on arm64:
        - dpdk
        - librte-meta-net
      - on ppc64el:
        - dpdk
        - librte-meta-net

  ovn:
    plugin: autotools
    source: https://github.com/ovn-org/ovn.git
    source-type: git
    source-branch: branch-22.09
    override-build: |
      # This OVS build is used as a build time dependency for OVN and not the
      # version installed.  See the `ovs` part above for the installed
      # artifact.
      cd ovs
      ./boot.sh
      ./configure \
        --prefix=/usr \
        --localstatedir=/var \
        --enable-ssl \
        --sysconfdir=/etc
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      cd ..
      ./boot.sh
      ./configure \
        --prefix=/usr \
        --localstatedir=/var \
        --enable-ssl \
        --sysconfdir=/etc
      make -j$CRAFT_PARALLEL_BUILD_COUNT
      make check TESTSUITEFLAGS="-j $CRAFT_PARALLEL_BUILD_COUNT"
      make install DESTDIR=$CRAFT_PART_INSTALL
    override-stage: |
      craftctl set version=$(git -C $CRAFT_PART_SRC describe --always | sed -e 's/-/+git/;y/-/./' | sed -s 's/^v//')
      craftctl default
    build-packages:
      - autoconf
      - automake
      - bzip2
      - graphviz
      - libcap-ng-dev
      - libnuma-dev
      - libpcap-dev
      - libssl-dev
      - libtool
      - libudev-dev
      - libunbound-dev
      - openssl
      - pkg-config
      - procps
      - python3-all-dev
      - python3-setuptools
      - python3-sortedcontainers
      - python3-sphinx
      - tcpdump

  ovs-wrapper:
    source: ./snap/local/snap-wrappers/ovs
    plugin: dump
    organize:
      ovs-wrapper: bin/ovs-wrapper
